### ISSUE TITLE
Black background on in-game menu bar panels

### ISSUE THREAD

**Issue by Kiwzi** [hawkeye-stan/msfs-2024-popout-panel-manager#12]
Hi,

Maybe out of scope for this project, but gonna ask anyway.
Lets say you pop out the atc window and move it to another screen, this window will still retain its transparent background from where it was pop'd out from, it would be nice if there was an option to choose plain black background (or take it further and make it a user defined color).

**Comment by hawkeye-stan** [comment]
Unfortunately, POPM won't be able to change pop out background color since it is controlled by the game itself and not Windows. The only thing it can do is changed the pop out title bar color.
