### ISSUE TITLE
MSFS2024 POPM freezes during initialization

### ISSUE THREAD

**Issue by KilstormMcBride** [hawkeye-stan/msfs-2024-popout-panel-manager#2]
I was able to get my A2A tablet to pop out when setting up and it worked just like it did in FS20. However, now everytime I click on POPM to do its thing it just locks up before targeting any panels. I have to close POPM and not use it. Any thoughts on what I am doing wrong?

**Comment by Jeffrey8608** [comment]
I have the same! Might be because it’s in early stage for 24!
